# flake8: noqa
# Conda environment specification. Details about the Conda environment file format:
# https://conda.io/docs/user-guide/tasks/manage-environments.html#create-env-file-manually

name: training_env
dependencies:
  - python=3.10.0
  - scikit-learn=0.24.1
  - pandas=1.4.2
  - matplotlib=3.5.2
  - pip:
    - azureml-defaults==1.40
    - dotnetcore2==3.1.23   
channels:
  - conda-forge
